### ISSUE TITLE
Getting error : TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by reddwarf666** [boukeversteegh/pptpd-monitor#10]
Hi Bouke,

Trying to use you script to gain some insights in our (inherited) VPN server.
When running the script I get this error:

Traceback (most recent call last):
  File "/home/stevenspierenburg/pptpd-monitor-master/src/pptpd-monitor.py", line 296, in <module>
    monitor.monitor()
  File "/home/stevenspierenburg/pptpd-monitor-master/src/pptpd-monitor.py", line 65, in monitor
    userstats    = self.get_userstats(sessionlist)
  File "/home/stevenspierenburg/pptpd-monitor-master/src/pptpd-monitor.py", line 188, in get_userstats
    for session in sessions:
TypeError: 'NoneType' object is not iterable

Some information
-----------------

Python version:
Python 3.6.5

Linux version (runs in AWS):
Linux version 4.9.70-22.55.amzn1.x86_64 (mockbuild@gobi-build-60007) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) ) #1 SMP Wed Dec 20 23:36:28 UTC 2017

Disclaimer:
Relative n00b on Linux but willing to learn and experiment :-)
(I have backups...)

**Comment by boukeversteegh** [comment]
Thanks for your question.

You need to specify the logfile location where pptpd writes its logs. It is different per system.

Please try with the option -f (for example `python3 pptpd-monitor.py -f /var/log/ppp/pptpd.log`)

I've improved the file checker so at least it lets you know that the file couldn't be found, instead of this strange error message.
